In [1]:
import numpy as np

In [8]:
arr1=np.array((1,2,4,7,8,9,4,5,6,7,9))

In [9]:
print("single dimentional:",arr1)

single dimentional: [1 2 4 7 8 9 4 5 6 7 9]


In [6]:
arr1.dtype

dtype('int64')

In [11]:
arr2=np.array([[10,20,30,40],[100,200,300,400]])
print("2-d arrays:\n",arr2)

2-d arrays:
 [[ 10  20  30  40]
 [100 200 300 400]]


In [12]:
#checking thair dimensions:
print("arr1:",arr1.ndim)
print("arr2:",arr2.ndim)

arr1: 1
arr2: 2


In [15]:
arr3=np.array([[[1,2,3,4],[10,20,30,40],[100,200,300,400]]])
print("3-d array:\n",arr3)
print("arr3:",arr3.ndim)

3-d array:
 [[[  1   2   3   4]
  [ 10  20  30  40]
  [100 200 300 400]]]
arr3: 3


In [16]:
#for casual cheking with data frames :
import pandas as pd

In [25]:
d_frame=pd.Series(arr1)
print(d_frame)

0     1
1     2
2     4
3     7
4     8
5     9
6     4
7     5
8     6
9     7
10    9
dtype: int64


In [26]:
#array to data frame
#here the data frame support only the 2-d arry for printing other wise the print function will show error message:
d_frame=pd.DataFrame(arr2)
print(d_frame)

     0    1    2    3
0   10   20   30   40
1  100  200  300  400


In [27]:
d_frame.shape

(2, 4)

In [28]:
#data frame to array
check1=np.array(d_frame)

In [29]:
print(check1)

[[ 10  20  30  40]
 [100 200 300 400]]


In [34]:
print("1-D:\t",arr1,"\n")
print("2-D:\t",arr2,"\n")
print("3-D:\t",arr3)

1-D:	 [1 2 4 7 8 9 4 5 6 7 9] 

2-D:	 [[ 10  20  30  40]
 [100 200 300 400]] 

3-D:	 [[[  1   2   3   4]
  [ 10  20  30  40]
  [100 200 300 400]]]


In [41]:
#nupy array indexing with step value:
print(arr1)
print(arr1[0:7])

[1 2 4 7 8 9 4 5 6 7 9]
[1 2 4 7 8 9 4]


In [44]:
#half of the elements are printing:
print("first half of the elements:",arr1[:len(arr1)//2])

first half of the elements: [1 2 4 7 8]


In [45]:
for i in arr1:
    print(i)

1
2
4
7
8
9
4
5
6
7
9


In [49]:
#iterating the 3-D array in one loop:
for i in np.nditer(arr3[:,::1]):
    print(i)

1
2
3
4
10
20
30
40
100
200
300
400


In [67]:
arr2.shape

(2, 4)

In [68]:
#doubt:ask to sir:
arr3.shape

(1, 3, 4)

In [69]:
np.ndim(arr3)

3

In [70]:
arr1.shape

(11,)

In [73]:
#accessign the nd arry elements:
#element - 1st row and first column
print(arr2[0,0])

10


In [76]:
#3-d arrray:
print(arr3[0,2,2])

300


In [81]:
#for the absolute we willl create another array with -ve value
arr4=np.array([-10,-20,-400,-183,142])
print(abs(arr4))

[ 10  20 400 183 142]


In [82]:
#reshaping
#add or remove from the existing array

In [84]:
np.array_split(arr1,2)

[array([1, 2, 4, 7, 8, 9]), array([4, 5, 6, 7, 9])]

In [87]:
np.array_split(arr2,2)

[array([[10, 20, 30, 40]]), array([[100, 200, 300, 400]])]

In [88]:
np.array_split(arr3,3)

[array([[[  1,   2,   3,   4],
         [ 10,  20,  30,  40],
         [100, 200, 300, 400]]]),
 array([], shape=(0, 3, 4), dtype=int64),
 array([], shape=(0, 3, 4), dtype=int64)]

In [90]:
np.array_split(arr1,5)

[array([1, 2, 4]), array([7, 8]), array([9, 4]), array([5, 6]), array([7, 9])]

In [103]:
print(len(arr4))

5


In [106]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [107]:
#splitting the array:
print(arr1)

[1 2 4 7 8 9 4 5 6 7 9]


In [109]:
newarr2=np.array_split(arr1,3)

In [111]:
for i in newarr2:
    print(newarr2[i])

TypeError: only integer scalar arrays can be converted to a scalar index

In [117]:
print(newarr2[0])
print(newarr2[1])
print(newarr2[2])

[1 2 4 7]
[8 9 4 5]
[6 7 9]


In [118]:
##searching arrays

In [126]:
arr1

[1 2 4 7 8 9 4 5 6 7 9]
(array([], dtype=int64),)


In [129]:
arr = np.array([1, 2, 1, 1, 5, 6, 7, 8])

x = np.where(arr == 1)

print(x)

(array([0, 2, 3]),)


In [134]:
arr=np.array((1,2,3,4,5,2,3,5,6,7,8))
x=np.where(arr==5)
print(x)

(array([4, 7]),)


In [136]:
x = np.searchsorted(arr, 6)
print(x)

8


In [138]:
#sorting:
arr=np.array((2,5,2,8,0,3,6,8))
print(np.sort(arr))

[0 2 2 3 5 6 8 8]


In [139]:
arr=np.array(("sanath","ravi","parmesh","azar"))
print(np.sort(arr))

['azar' 'parmesh' 'ravi' 'sanath']


In [140]:
#we can also sort the 2-d array:
arr=np.array([[20,10,29],[0,20,83]])
print(np.sort(arr))

[[10 20 29]
 [ 0 20 83]]


In [143]:
arr=np.array([1,2,3,4])
x=[True,False,True,True]
print(arr[x])

[1 3 4]


In [144]:
#nupy rondom class working:
#we can predict theese numbers:
#machine will generate this:
from numpy import random

In [153]:
x=random.randint(100)
x

77

In [148]:
print(x)

88


In [154]:
x=random.rand(10)
x

array([0.88562907, 0.22932804, 0.90857795, 0.2838597 , 0.76885629,
       0.87201837, 0.5121362 , 0.89441225, 0.67149354, 0.03825343])

In [170]:
#generating 10 randoom numbers in given range:
#and this method is also called as the creating the 2-d array:
x=random.randint(100,size=10)
x

array([ 6, 16, 29, 50,  6,  0, 99, 11, 88, 33])

In [158]:
#creating the 3-d array from the rndom :
x=random.randint(100,size=(3,10))
x

array([[40, 55, 86, 42, 85, 35, 18, 13, 11, 35],
       [66, 31, 61, 65, 23, 49, 65, 30, 90,  3],
       [90, 53, 95, 32, 45, 85, 31, 10, 52, 69]])

In [159]:
x.shape

(3, 10)

In [171]:
#upto now we have created random array:
# but now we can get the random element from the generatd arry:
#only for the 1-d array
y=random.choice(x)
y

29

In [174]:
#now we can get the choice of number from the 2-d array by using the size:
arr2 = random.choice([3, 5, 7, 9], size=(3, 5))
arr2

array([[5, 7, 9, 7, 3],
       [9, 9, 5, 7, 7],
       [5, 5, 5, 9, 5]])

In [179]:
#rndom permutatiions
arr=np.array([1,2,3,4])
random.shuffle(arr)
print(arr)

[1 3 2 4]


In [181]:
print(random.permutation(arr))

[4 1 2 3]


In [189]:
#zip method:
x1=[1,2,3,93,82]
x2=[4,3,2,3,4,]
z=[]
for i,j in zip(x1,x2):
    z.append(i+j)
print(z)

[5, 5, 5, 96, 86]


In [199]:
#arithmatic operations:
print(np.add(x1,x2))
print(np.subtract(x1,x2))
print(np.multiply(x1,x2))
print(np.divide(x1,x2))
print(np.power(x1,x2))
print(np.mod(x1,x2))
print(np.remainder(x1,x2))
print(np.divmod(x1,x2))
print(np.(x1,x2))

[ 5  5  5 96 86]
[-3 -1  1 90 78]
[  4   6   6 279 328]
[ 0.25        0.66666667  1.5        31.         20.5       ]
[       1        8        9   804357 45212176]
[1 2 1 0 2]
[1 2 1 0 2]
(array([ 0,  0,  1, 31, 20]), array([1, 2, 1, 0, 2]))
